---
deployment:
  tasks:
    - export REPOPATH=/home/estartby/repositories/estart.pro/*
    - export SITEPATH=/home/estartby/public_html/
    - /bin/rsync -rav --exclude '.git' --exclude '.cpanel.yml' --del $REPOPATH $SITEPATH
    -

